### ISSUE TITLE
Always getting [config-0]: No files specified

### ISSUE THREAD

**Issue by mnieber** [JorgenEvens/multi-sass#1]
Using:
  - multi-sass@1.0.0
  - node-sass@4.5.0

My problem is that I always get `[config-0]: No files specified`

`multi-sass --file ./test.scss --output /tmp/test.css`
[config-0]: No files specified

**Comment by JorgenEvens** [comment]
Hi @mnieber,

Looks like I made an error in the example, that should actually read `--input` instead of `--file`.
The example is fixed as of https://github.com/JorgenEvens/multi-sass/commit/9dd49603d5d674865c2e6ac1602e5e9cebdce308.

Thanks for reporting this!
